name: .NET

on:
  push:
    branches: [ main ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Set Version
      run: echo "BUILD_VERSION=$(date +%Y.%m.%d).$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack DotNet.VarSub.Console -p:AssemblyVersion=${{ env.BUILD_VERSION }} -p:AssemblyFileVerson=${{ env.BUILD_VERSION }} -p:FileVersion=${{ env.BUILD_VERSION }} -p:PackageVersion=${{ env.BUILD_VERSION }} --output $GITHUB_WORKSPACE
    - name: Publish
      run: dotnet nuget push $GITHUB_WORKSPACE/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
